FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ARG BASE_PATH="/severity-5"
ENTRYPOINT ["sh", "-c", "exec streamlit run severity-5/app.py --server.port=8501 --server.address=0.0.0.0 --server.baseUrlPath=${BASE_PATH}"]